"""add cascade delete to foreign keys

Revision ID: 98ecdbe85cd7
Revises: 75d1818cde45
Create Date: 2025-12-07 23:24:47.095729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '98ecdbe85cd7'
down_revision: Union[str, Sequence[str], None] = '75d1818cde45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('asset_category_ibfk_1'), 'asset_category', type_='foreignkey')
    op.drop_constraint(op.f('asset_category_ibfk_2'), 'asset_category', type_='foreignkey')
    op.create_foreign_key(None, 'asset_category', 'category', ['category_id'], ['category_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_category', 'asset', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('asset_tag_ibfk_2'), 'asset_tag', type_='foreignkey')
    op.drop_constraint(op.f('asset_tag_ibfk_1'), 'asset_tag', type_='foreignkey')
    op.create_foreign_key(None, 'asset_tag', 'asset', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_tag', 'tag', ['tag_id'], ['tag_id'], ondelete='CASCADE')
    #op.drop_index(op.f('idx_audit_user'), table_name='audit_log')
    #op.create_index(op.f('ix_audit_log_log_id'), 'audit_log', ['log_id'], unique=False)
    op.drop_constraint(op.f('fk_audit_user'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'user', ['user_id'], ['user_id'])
    #op.drop_index(op.f('idx_category_name'), table_name='category')
    #op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=False)
    op.drop_constraint(op.f('fk_category_parent'), 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'category', ['parent_category_id'], ['category_id'])
    #op.create_index(op.f('ix_comment_comment_id'), 'comment', ['comment_id'], unique=False)
    op.drop_constraint(op.f('fk_comment_user'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['user_id'])
    #op.create_index(op.f('ix_export_job_job_id'), 'export_job', ['job_id'], unique=False)
    op.drop_constraint(op.f('fk_exportjob_user'), 'export_job', type_='foreignkey')
    op.create_foreign_key(None, 'export_job', 'user', ['user_id'], ['user_id'])
    op.alter_column('metadata', 'duration',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=50),
               existing_nullable=True)
    #op.create_index(op.f('ix_password_reset_token_token_id'), 'password_reset_token', ['token_id'], unique=False)
    op.drop_constraint(op.f('fk_prt_user'), 'password_reset_token', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_token', 'user', ['user_id'], ['user_id'])
    #op.drop_index(op.f('uq_permission_resource_action'), table_name='permission')
    #op.create_index(op.f('ix_permission_permission_id'), 'permission', ['permission_id'], unique=False)
    #op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.drop_constraint(op.f('fk_rp_role'), 'role_permission', type_='foreignkey')
    op.drop_constraint(op.f('fk_rp_permission'), 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'role', ['role_id'], ['role_id'])
    op.create_foreign_key(None, 'role_permission', 'permission', ['permission_id'], ['permission_id'])
    #op.drop_index(op.f('idx_sharelink_token'), table_name='share_link')
    #op.drop_index(op.f('token'), table_name='share_link')
    #op.create_index(op.f('ix_share_link_link_id'), 'share_link', ['link_id'], unique=False)
    #op.create_index(op.f('ix_share_link_token'), 'share_link', ['token'], unique=True)
    op.drop_constraint(op.f('fk_sharelink_user'), 'share_link', type_='foreignkey')
    op.create_foreign_key(None, 'share_link', 'user', ['created_by_user_id'], ['user_id'])
    #op.drop_index(op.f('idx_tag_name'), table_name='tag')
    #op.create_index(op.f('ix_tag_tag_id'), 'tag', ['tag_id'], unique=False)
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    #op.drop_index(op.f('idx_user_email'), table_name='user')
    #op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_user_role'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['role_id'])
    #op.drop_index(op.f('uq_asset_version_number'), table_name='version')
    #op.create_index(op.f('ix_version_version_id'), 'version', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_version_version_id'), table_name='version')
    op.create_index(op.f('uq_asset_version_number'), 'version', ['asset_id', 'version_number'], unique=True)
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_role'), 'user', 'role', ['role_id'], ['role_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_index(op.f('idx_user_email'), 'user', ['email'], unique=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_tag_tag_id'), table_name='tag')
    op.create_index(op.f('idx_tag_name'), 'tag', ['tag_name'], unique=False)
    op.drop_constraint(None, 'share_link', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sharelink_user'), 'share_link', 'user', ['created_by_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_share_link_token'), table_name='share_link')
    op.drop_index(op.f('ix_share_link_link_id'), table_name='share_link')
    op.create_index(op.f('token'), 'share_link', ['token'], unique=True)
    op.create_index(op.f('idx_sharelink_token'), 'share_link', ['token'], unique=False)
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key(op.f('fk_rp_permission'), 'role_permission', 'permission', ['permission_id'], ['permission_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_rp_role'), 'role_permission', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_index(op.f('ix_permission_permission_id'), table_name='permission')
    op.create_index(op.f('uq_permission_resource_action'), 'permission', ['resource', 'action'], unique=True)
    op.drop_constraint(None, 'password_reset_token', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prt_user'), 'password_reset_token', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_token_token_id'), table_name='password_reset_token')
    op.alter_column('metadata', 'duration',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'export_job', type_='foreignkey')
    op.create_foreign_key(op.f('fk_exportjob_user'), 'export_job', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_export_job_job_id'), table_name='export_job')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comment_user'), 'comment', 'user', ['user_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_comment_comment_id'), table_name='comment')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(op.f('fk_category_parent'), 'category', 'category', ['parent_category_id'], ['category_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.create_index(op.f('idx_category_name'), 'category', ['category_name'], unique=False)
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audit_user'), 'audit_log', 'user', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_log_log_id'), table_name='audit_log')
    op.create_index(op.f('idx_audit_user'), 'audit_log', ['user_id'], unique=False)
    op.drop_constraint(None, 'asset_tag', type_='foreignkey')
    op.drop_constraint(None, 'asset_tag', type_='foreignkey')
    op.create_foreign_key(op.f('asset_tag_ibfk_1'), 'asset_tag', 'asset', ['asset_id'], ['asset_id'])
    op.create_foreign_key(op.f('asset_tag_ibfk_2'), 'asset_tag', 'tag', ['tag_id'], ['tag_id'])
    op.drop_constraint(None, 'asset_category', type_='foreignkey')
    op.drop_constraint(None, 'asset_category', type_='foreignkey')
    op.create_foreign_key(op.f('asset_category_ibfk_2'), 'asset_category', 'category', ['category_id'], ['category_id'])
    op.create_foreign_key(op.f('asset_category_ibfk_1'), 'asset_category', 'asset', ['asset_id'], ['asset_id'])
    # ### end Alembic commands ###
